// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"
#include "../spaUI/uiSpaShared.h"

void uiHeatClick(lv_event_t * e)
{
	spaLvglClickHeat(e);
}

void uiPumpClick1(lv_event_t * e)
{
		spaLvglClickPump(e,1);
}

void uiPumpClick2(lv_event_t * e)
{
	spaLvglClickPump(e,2);
}

void uiLightClick1(lv_event_t * e)
{
	spaLvglClickLight(e,1);
}
