// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"
#include "../spaUI/uiSpaShared.h"

void clickButton(lv_event_t *e)
{
	spaLvglClickButton(e);
}

void uiPumpClick(lv_event_t *e)
{
	spaLvglClickPump(e);
}

void uiLightClicked(lv_event_t *e)
{
	spaLvglClickLight(e);
}
