// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND 0
#define UI_THEME_COLOR_ACCESSORYONBKG 1
#define UI_THEME_COLOR_ACCESSORYOFFBKG 2
#define UI_THEME_COLOR_WIDGETBORDER 3
#define UI_THEME_COLOR_GRAPHBKG 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_SECOND_SCREEN 1

extern const ui_theme_variable_t _ui_theme_color_Background[2];
extern const ui_theme_variable_t _ui_theme_alpha_Background[2];

extern const ui_theme_variable_t _ui_theme_color_AccessoryOnBkg[2];
extern const ui_theme_variable_t _ui_theme_alpha_AccessoryOnBkg[2];

extern const ui_theme_variable_t _ui_theme_color_AccessoryOffBkg[2];
extern const ui_theme_variable_t _ui_theme_alpha_AccessoryOffBkg[2];

extern const ui_theme_variable_t _ui_theme_color_widgetBorder[2];
extern const ui_theme_variable_t _ui_theme_alpha_widgetBorder[2];

extern const ui_theme_variable_t _ui_theme_color_graphBkg[2];
extern const ui_theme_variable_t _ui_theme_alpha_graphBkg[2];

extern const uint32_t* ui_theme_colors[2];
extern const uint8_t* ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
