// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Background[2] = {0x1F313F, 0x1F313F};
const ui_theme_variable_t _ui_theme_alpha_Background[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_AccessoryOnBkg[2] = {0x72C0FF, 0x72C0FF};
const ui_theme_variable_t _ui_theme_alpha_AccessoryOnBkg[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_AccessoryOffBkg[2] = {0x4779A1, 0x4779A1};
const ui_theme_variable_t _ui_theme_alpha_AccessoryOffBkg[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_widgetBorder[2] = {0x1F313F, 0x1F313F};
const ui_theme_variable_t _ui_theme_alpha_widgetBorder[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_graphBkg[2] = {0xC3C3C8, 0xC3C3C8};
const ui_theme_variable_t _ui_theme_alpha_graphBkg[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

