// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
lv_obj_t *ui_Loading_Screen;
lv_obj_t *ui_Loading_Pump_Off;
lv_obj_t *ui_pumpButton13;
lv_obj_t *ui_pumpLabel14;
lv_obj_t *ui_Loading_Pump_High;
lv_obj_t *ui_pumpButton10;
lv_obj_t *ui_pumpLabel11;
lv_obj_t *ui_Loading_Filter_Off;
lv_obj_t *ui_pumpButton12;
lv_obj_t *ui_pumpLabel13;
lv_obj_t *ui_Loading_Spa_Light_On;
lv_obj_t *ui_Spa_Light_Image3;
lv_obj_t *ui_Spa_Ligtht_Label3;
lv_obj_t *ui_Container3;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Loading_Filter_On;
lv_obj_t *ui_pumpButton9;
lv_obj_t *ui_pumpLabel10;
lv_obj_t *ui_Loading_Spa_Light_Off;
lv_obj_t *ui_lampButton7;
lv_obj_t *ui_lampLabel2;


// SCREEN: ui_Spa_Screen
void ui_Spa_Screen_screen_init(void);
lv_obj_t *ui_Spa_Screen;
lv_obj_t *ui_uiThermostat;
lv_obj_t *ui_uiThermostatLabel;
lv_obj_t *ui_uiThermostatArc;
lv_obj_t *ui_uiClock;
lv_obj_t *ui_uiClockLabel;
lv_obj_t *ui_uiPump_1;
lv_obj_t *ui_uiPumpButton_1;
lv_obj_t *ui_uiPumpLabel_1;
lv_obj_t *ui_uiPump_2;
lv_obj_t *ui_uiPumpButton_2;
lv_obj_t *ui_uiPumpLabel_2;
lv_obj_t *ui_uiLight_1;
lv_obj_t *ui_uiLightButton_1;
lv_obj_t *ui_uiLightLabel_1;
lv_obj_t *ui_uiFilter;
lv_obj_t *ui_uiFilterButton;
lv_obj_t *ui_uiFilterLabel;


// SCREEN: ui_Light_Samples
void ui_Light_Samples_screen_init(void);
lv_obj_t *ui_Light_Samples;
lv_obj_t *ui_OffSample;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Lamp8;
lv_obj_t *ui_lampButton8;
lv_obj_t *ui_lampLabel5;
lv_obj_t *ui_Lamp2;
lv_obj_t *ui_lampButton2;
lv_obj_t *ui_Container2;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Lamp5;
lv_obj_t *ui_lampButton5;
lv_obj_t *ui_lampLabel4;
lv_obj_t *ui_Lamp6;
lv_obj_t *ui_lampButton6;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Sample_Spa_Light_1;
lv_obj_t *ui_Spa_Light_Image;
lv_obj_t *ui_Spa_Ligtht_Label;
lv_obj_t *ui_Lamp3;
lv_obj_t *ui_lampButton3;


// SCREEN: ui_Pump_Samples
void ui_Pump_Samples_screen_init(void);
lv_obj_t *ui_Pump_Samples;
lv_obj_t *ui_Off_Sample;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Pump_Off;
lv_obj_t *ui_pumpButton7;
lv_obj_t *ui_pumpLabel7;
lv_obj_t *ui_Lamp1;
lv_obj_t *ui_pumpLabel;
lv_obj_t *ui_Low_Sample;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Pump_Off2;
lv_obj_t *ui_lampButton10;
lv_obj_t *ui_lampLabel3;
lv_obj_t *ui_Lamp7;
lv_obj_t *ui_lampButton4;
lv_obj_t *ui_High_Sample;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Pump_Off3;
lv_obj_t *ui_pumpButton2;
lv_obj_t *ui_pumpLabel3;
lv_obj_t *ui_Lamp9;
lv_obj_t *ui_pumpLabel1;


// SCREEN: ui_Filter_Samples
void ui_Filter_Samples_screen_init(void);
lv_obj_t *ui_Filter_Samples;
lv_obj_t *ui_Off_Sample1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Pump_Off1;
lv_obj_t *ui_pumpButton1;
lv_obj_t *ui_pumpLabel2;
lv_obj_t *ui_Pump_Off8;
lv_obj_t *ui_pumpButton11;
lv_obj_t *ui_pumpLabel12;
lv_obj_t *ui_High_Sample1;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Filter_On;
lv_obj_t *ui_pumpButton3;
lv_obj_t *ui_pumpLabel5;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Loading_Screen_screen_init();
ui_Spa_Screen_screen_init();
ui_Light_Samples_screen_init();
ui_Pump_Samples_screen_init();
ui_Filter_Samples_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Loading_Screen);
}
