// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
lv_obj_t *ui_Loading_Screen;
lv_obj_t *ui_LoadingContainer;
lv_obj_t *ui_LoadingLabel;
lv_obj_t *ui_uiPumpLoading;
lv_obj_t *ui_uiFilterLoading;
lv_obj_t *ui_uiLightLoading;
lv_obj_t *ui_uiLight2;


// SCREEN: ui_Spa_Screen
void ui_Spa_Screen_screen_init(void);
lv_obj_t *ui_Spa_Screen;
lv_obj_t *ui_uiThermostat;
lv_obj_t *ui_uiThermostatLabel;
lv_obj_t *ui_uiThermostatArc;
lv_obj_t *ui_uiClock;
lv_obj_t *ui_uiClockLabel;
lv_obj_t *ui_uiPump1;
lv_obj_t *ui_uiPump2;
lv_obj_t *ui_uiLight1;
lv_obj_t *ui_uiFilter;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Loading_Screen_screen_init();
ui_Spa_Screen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Loading_Screen);
}
