// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _SPA_UI_H
#define _SPA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
extern lv_obj_t *ui_Loading_Screen;
extern lv_obj_t *ui_Loading_Pump_Off;
extern lv_obj_t *ui_pumpButton13;
extern lv_obj_t *ui_pumpLabel14;
extern lv_obj_t *ui_Loading_Pump_High;
extern lv_obj_t *ui_pumpButton10;
extern lv_obj_t *ui_pumpLabel11;
extern lv_obj_t *ui_Loading_Filter_Off;
extern lv_obj_t *ui_pumpButton12;
extern lv_obj_t *ui_pumpLabel13;
extern lv_obj_t *ui_Loading_Spa_Light_On;
extern lv_obj_t *ui_Spa_Light_Image3;
extern lv_obj_t *ui_Spa_Ligtht_Label3;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Loading_Filter_On;
extern lv_obj_t *ui_pumpButton9;
extern lv_obj_t *ui_pumpLabel10;
extern lv_obj_t *ui_Loading_Spa_Light_Off;
extern lv_obj_t *ui_lampButton7;
extern lv_obj_t *ui_lampLabel2;
// SCREEN: ui_Spa_Screen
void ui_Spa_Screen_screen_init(void);
extern lv_obj_t *ui_Spa_Screen;
extern lv_obj_t *ui_uiThermostat;
extern lv_obj_t *ui_uiThermostatLabel;
extern lv_obj_t *ui_uiThermostatArc;
extern lv_obj_t *ui_uiClock;
extern lv_obj_t *ui_uiClockLabel;
extern lv_obj_t *ui_uiPump_1;
extern lv_obj_t *ui_uiPumpButton_1;
extern lv_obj_t *ui_uiPumpLabel_1;
extern lv_obj_t *ui_uiPump_2;
extern lv_obj_t *ui_uiPumpButton_2;
extern lv_obj_t *ui_uiPumpLabel_2;
extern lv_obj_t *ui_uiLight_1;
extern lv_obj_t *ui_uiLightButton_1;
extern lv_obj_t *ui_uiLightLabel_1;
extern lv_obj_t *ui_uiFilter;
extern lv_obj_t *ui_uiFilterButton;
extern lv_obj_t *ui_uiFilterLabel;
// SCREEN: ui_Light_Samples
void ui_Light_Samples_screen_init(void);
extern lv_obj_t *ui_Light_Samples;
extern lv_obj_t *ui_OffSample;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Lamp8;
extern lv_obj_t *ui_lampButton8;
extern lv_obj_t *ui_lampLabel5;
extern lv_obj_t *ui_Lamp2;
extern lv_obj_t *ui_lampButton2;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Lamp5;
extern lv_obj_t *ui_lampButton5;
extern lv_obj_t *ui_lampLabel4;
extern lv_obj_t *ui_Lamp6;
extern lv_obj_t *ui_lampButton6;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Sample_Spa_Light_1;
extern lv_obj_t *ui_Spa_Light_Image;
extern lv_obj_t *ui_Spa_Ligtht_Label;
extern lv_obj_t *ui_Lamp3;
extern lv_obj_t *ui_lampButton3;
// SCREEN: ui_Pump_Samples
void ui_Pump_Samples_screen_init(void);
extern lv_obj_t *ui_Pump_Samples;
extern lv_obj_t *ui_Off_Sample;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Pump_Off;
extern lv_obj_t *ui_pumpButton7;
extern lv_obj_t *ui_pumpLabel7;
extern lv_obj_t *ui_Lamp1;
extern lv_obj_t *ui_pumpLabel;
extern lv_obj_t *ui_Low_Sample;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Pump_Off2;
extern lv_obj_t *ui_lampButton10;
extern lv_obj_t *ui_lampLabel3;
extern lv_obj_t *ui_Lamp7;
extern lv_obj_t *ui_lampButton4;
extern lv_obj_t *ui_High_Sample;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Pump_Off3;
extern lv_obj_t *ui_pumpButton2;
extern lv_obj_t *ui_pumpLabel3;
extern lv_obj_t *ui_Lamp9;
extern lv_obj_t *ui_pumpLabel1;
// SCREEN: ui_Filter_Samples
void ui_Filter_Samples_screen_init(void);
extern lv_obj_t *ui_Filter_Samples;
extern lv_obj_t *ui_Off_Sample1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Pump_Off1;
extern lv_obj_t *ui_pumpButton1;
extern lv_obj_t *ui_pumpLabel2;
extern lv_obj_t *ui_Pump_Off8;
extern lv_obj_t *ui_pumpButton11;
extern lv_obj_t *ui_pumpLabel12;
extern lv_obj_t *ui_High_Sample1;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Filter_On;
extern lv_obj_t *ui_pumpButton3;
extern lv_obj_t *ui_pumpLabel5;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui__temporary_image );
LV_IMG_DECLARE( ui_img_pumpoff_png);   // assets/pumpOff.png
LV_IMG_DECLARE( ui_img_pumphigh_png);   // assets/pumpHigh.png
LV_IMG_DECLARE( ui_img_filteron_png);   // assets/filterOn.png
LV_IMG_DECLARE( ui_img_lighton_png);   // assets/lightOn.png
LV_IMG_DECLARE( ui_img_lightoff_png);   // assets/lightOff.png
LV_IMG_DECLARE( ui_img_pumplow_png);   // assets/pumpLow.png


LV_FONT_DECLARE( ui_font_Montserrat_Bold_14);
LV_FONT_DECLARE( ui_font_Montserrat_Bold_16);
LV_FONT_DECLARE( ui_font_Montserrat_Bold_18);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
