// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _SPA_UI_H
#define _SPA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
extern lv_obj_t *ui_Loading_Screen;
extern lv_obj_t *ui_Loading_Pump_Off;
extern lv_obj_t *ui_pumpButton13;
extern lv_obj_t *ui_pumpLabel14;
extern lv_obj_t *ui_Loading_Pump_High;
extern lv_obj_t *ui_pumpButton10;
extern lv_obj_t *ui_pumpLabel11;
extern lv_obj_t *ui_Loading_Filter_Off;
extern lv_obj_t *ui_pumpButton12;
extern lv_obj_t *ui_pumpLabel13;
extern lv_obj_t *ui_Loading_Spa_Light_On;
extern lv_obj_t *ui_Spa_Light_Image3;
extern lv_obj_t *ui_Spa_Ligtht_Label3;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Loading_Filter_On;
extern lv_obj_t *ui_pumpButton9;
extern lv_obj_t *ui_pumpLabel10;
extern lv_obj_t *ui_Loading_Spa_Light_Off;
extern lv_obj_t *ui_lampButton7;
extern lv_obj_t *ui_lampLabel2;
// SCREEN: ui_Spa_Screen
void ui_Spa_Screen_screen_init(void);
extern lv_obj_t *ui_Spa_Screen;
extern lv_obj_t *ui_uiThermostat;
extern lv_obj_t *ui_uiThermostatLabel;
extern lv_obj_t *ui_uiThermostatArc;
extern lv_obj_t *ui_uiClock;
extern lv_obj_t *ui_uiClockLabel;
extern lv_obj_t *ui_uiPump_1;
extern lv_obj_t *ui_uiPumpButton_1;
extern lv_obj_t *ui_uiPumpLabel_1;
void ui_event_uiPump_2( lv_event_t * e);
extern lv_obj_t *ui_uiPump_2;
extern lv_obj_t *ui_uiPumpButton_2;
extern lv_obj_t *ui_uiPumpLabel_2;
void ui_event_uiLight_1( lv_event_t * e);
extern lv_obj_t *ui_uiLight_1;
extern lv_obj_t *ui_uiLightButton_1;
extern lv_obj_t *ui_uiLightLabel_1;
extern lv_obj_t *ui_uiFilter;
extern lv_obj_t *ui_uiFilterButton;
extern lv_obj_t *ui_uiFilterLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui__temporary_image );
LV_IMG_DECLARE( ui_img_uipumpoff_png);   // assets/uiPumpOff.png
LV_IMG_DECLARE( ui_img_uipumphigh_png);   // assets/uiPumpHigh.png
LV_IMG_DECLARE( ui_img_filteron_png);   // assets/filterOn.png
LV_IMG_DECLARE( ui_img_lighton_png);   // assets/lightOn.png
LV_IMG_DECLARE( ui_img_lightoff_png);   // assets/lightOff.png
LV_IMG_DECLARE( ui_img_uipumplow_png);   // assets/uiPumpLow.png


LV_FONT_DECLARE( ui_font_Montserrat_Bold_14);
LV_FONT_DECLARE( ui_font_Montserrat_Bold_16);
LV_FONT_DECLARE( ui_font_Montserrat_Bold_18);
LV_FONT_DECLARE( ui_font_Open_Sans_12);
LV_FONT_DECLARE( ui_font_Open_Sans_14);
LV_FONT_DECLARE( ui_font_Open_Sans_16);
LV_FONT_DECLARE( ui_font_Open_Sans_18);
LV_FONT_DECLARE( ui_font_Open_Sans_20);
LV_FONT_DECLARE( ui_font_Open_Sans_24);
LV_FONT_DECLARE( ui_font_Open_Sans_26);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_12);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_14);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_16);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_18);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_20);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_24);
LV_FONT_DECLARE( ui_font_Open_Sans_Bold_26);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
