// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _SPA_UI_H
#define _SPA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Spa_Screen
void ui_Spa_Screen_screen_init(void);
extern lv_obj_t *ui_Spa_Screen;
extern lv_obj_t *ui_Current_Temperature;
extern lv_obj_t *ui_Temp_History;
extern lv_obj_t *ui_Temp_History_Xaxis;
extern lv_obj_t *ui_Temp_History_Yaxis1;
extern lv_obj_t *ui_Temp_History_Yaxis2;
extern lv_obj_t *ui_Heater_History;
extern lv_obj_t *ui_Heater_History_Xaxis;
extern lv_obj_t *ui_Heater_History_Yaxis1;
extern lv_obj_t *ui_Heater_History_Yaxis2;
extern lv_obj_t *ui_Filter_History;
extern lv_obj_t *ui_Filter_History_Xaxis;
extern lv_obj_t *ui_Filter_History_Yaxis1;
extern lv_obj_t *ui_Filter_History_Yaxis2;
extern lv_obj_t *ui_Pump_1;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
