// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA
#include <Arduino.h>
#include "ui.h"


void uiLightClicked(lv_event_t *e)
{
	// Your code here
	log_i("uiLightClicked");
}

void heatRangeSwtich(lv_event_t *e)
{
	// Your code here
	log_i("heatRangeSwtich");
}


void uiPumpClick(lv_event_t * e)
{
	// Your code here
			log_i("uiPumpClick");
}
