// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"

void uiPumpClicked2(lv_event_t * e)
{
	// Your code here
}

void uiLightClicked(lv_event_t * e)
{
	// Your code here
}
