// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Background[1] = {0xBFE0F8};
const ui_theme_variable_t _ui_theme_alpha_Background[1] = {255};

const ui_theme_variable_t _ui_theme_color_AccessoryOnBkg[1] = {0x07F42C};
const ui_theme_variable_t _ui_theme_alpha_AccessoryOnBkg[1] = {255};

const ui_theme_variable_t _ui_theme_color_AccessoryOffBkg[1] = {0xA3E5AE};
const ui_theme_variable_t _ui_theme_alpha_AccessoryOffBkg[1] = {255};

const ui_theme_variable_t _ui_theme_color_widgetBorder[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_widgetBorder[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

