// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _SPA_UI_COMP_HOOK_H
#define _SPA_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_uiFilter_create_hook( lv_obj_t *comp );
void ui_comp_uiLight_create_hook( lv_obj_t *comp );
void ui_comp_uiPump_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
