// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _UI_COMP_UIFILTER_H
#define _UI_COMP_UIFILTER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT uiFilter
#define UI_COMP_UIFILTER_UIFILTER 0
#define UI_COMP_UIFILTER_BUTTON 1
#define UI_COMP_UIFILTER_LABEL 2
#define _UI_COMP_UIFILTER_NUM 3
lv_obj_t *ui_uiFilter_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
