// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_adjustThermostatScreen_screen_init(void)
{
ui_adjustThermostatScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_adjustThermostatScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_adjustThermostatScreen, LV_SCROLLBAR_MODE_OFF);
lv_obj_add_event_cb(ui_adjustThermostatScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_adjustThermostatScreen);
ui_object_set_themeable_style_property(ui_adjustThermostatScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_adjustThermostatScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_border_color(ui_adjustThermostatScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_adjustThermostatScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_adjustThermostatScreen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_adjustThermostatScreen, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_adjustThermostatScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_adjustThermostatScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_adjustThermostatScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_adjustThermostatScreen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_adjustThermostatScreen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_adjustThermostatScreen, &ui_font_Open_Sans_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiThermostatPlaceholder3 = lv_obj_create(ui_adjustThermostatScreen);
lv_obj_remove_style_all(ui_uiThermostatPlaceholder3);
lv_obj_set_width( ui_uiThermostatPlaceholder3, 200);
lv_obj_set_height( ui_uiThermostatPlaceholder3, 110);
lv_obj_remove_flag( ui_uiThermostatPlaceholder3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uiThermostatPlaceholder3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_uiThermostatPlaceholder3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiThermostatPlaceholder3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiThermostatPlaceholder3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_uiThermostatPlaceholder3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_uiThermostatPlaceholder3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_uiThermostatPlaceholder3, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiClock3 = lv_obj_create(ui_adjustThermostatScreen);
lv_obj_remove_style_all(ui_uiClock3);
lv_obj_set_width( ui_uiClock3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiClock3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_uiClock3, LV_ALIGN_TOP_RIGHT );
lv_obj_remove_flag( ui_uiClock3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uiClock3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_uiClock3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiClock3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiClock3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_uiClock3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_uiClock3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_uiClock3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiClock3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiClock3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiClock3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_uiClock3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiClockLabel3 = lv_label_create(ui_uiClock3);
lv_obj_set_width( ui_uiClockLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiClockLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_uiClockLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiClockLabel3,"Mon, 07 Oct 2024 @ 22:30");
lv_obj_set_style_pad_left(ui_uiClockLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiClockLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiClockLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiClockLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_uiClockLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_uiClockLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatControls2 = lv_obj_create(ui_adjustThermostatScreen);
lv_obj_remove_style_all(ui_HeatControls2);
lv_obj_set_width( ui_HeatControls2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_HeatControls2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_HeatControls2, 0 );
lv_obj_set_y( ui_HeatControls2, -127 );
lv_obj_set_align( ui_HeatControls2, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_HeatControls2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HeatControls2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_HeatControls2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatControls2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatControls2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_HeatControls2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_HeatControls2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_HeatControls2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_HeatControls2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiHeatState2 = lv_obj_create(ui_HeatControls2);
lv_obj_remove_style_all(ui_uiHeatState2);
lv_obj_set_width( ui_uiHeatState2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiHeatState2, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_uiHeatState2, 60 );
lv_obj_set_y( ui_uiHeatState2, 63 );
lv_obj_set_align( ui_uiHeatState2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uiHeatState2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_uiHeatState2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_uiHeatState2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_uiHeatState2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiHeatState2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
lv_obj_set_style_pad_left(ui_uiHeatState2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiHeatState2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiHeatState2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiHeatState2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_uiHeatState2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_uiHeatState2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_uiHeatState2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiHeatState2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heatBlankLabel2 = lv_label_create(ui_uiHeatState2);
lv_obj_set_width( ui_heatBlankLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heatBlankLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_heatBlankLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_heatBlankLabel2,"       ");

ui_heatStateSwitch2 = lv_switch_create(ui_uiHeatState2);
lv_obj_set_width( ui_heatStateSwitch2, 50);
lv_obj_set_height( ui_heatStateSwitch2, 25);
lv_obj_set_align( ui_heatStateSwitch2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_heatStateSwitch2, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_heatStateSwitch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE );    /// Flags

lv_obj_set_style_bg_color(ui_heatStateSwitch2, lv_color_hex(0x10AAF0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_heatStateSwitch2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_heatStateSwitch2, lv_color_hex(0xA2741E), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_heatStateSwitch2, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_object_set_themeable_style_property(ui_heatStateSwitch2, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_graphBkg);
ui_object_set_themeable_style_property(ui_heatStateSwitch2, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_graphBkg);

ui_heatSwtichLabel2 = lv_label_create(ui_uiHeatState2);
lv_obj_set_width( ui_heatSwtichLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heatSwtichLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_heatSwtichLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_heatSwtichLabel2,"Heat");

ui_uiTempRange2 = lv_obj_create(ui_HeatControls2);
lv_obj_remove_style_all(ui_uiTempRange2);
lv_obj_set_width( ui_uiTempRange2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiTempRange2, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_uiTempRange2, 60 );
lv_obj_set_y( ui_uiTempRange2, 63 );
lv_obj_set_align( ui_uiTempRange2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uiTempRange2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_uiTempRange2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_uiTempRange2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_uiTempRange2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiTempRange2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
lv_obj_set_style_pad_left(ui_uiTempRange2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiTempRange2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiTempRange2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiTempRange2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_uiTempRange2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_uiTempRange2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_uiTempRange2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiTempRange2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempRangeLowLabel3 = lv_label_create(ui_uiTempRange2);
lv_obj_set_width( ui_tempRangeLowLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempRangeLowLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempRangeLowLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempRangeLowLabel3,"Low");

ui_tempRangeSwitch2 = lv_switch_create(ui_uiTempRange2);
lv_obj_set_width( ui_tempRangeSwitch2, 50);
lv_obj_set_height( ui_tempRangeSwitch2, 25);
lv_obj_set_align( ui_tempRangeSwitch2, LV_ALIGN_CENTER );
lv_obj_add_state( ui_tempRangeSwitch2, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_tempRangeSwitch2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_bg_color(ui_tempRangeSwitch2, lv_color_hex(0x10AAF0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tempRangeSwitch2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_tempRangeSwitch2, lv_color_hex(0xA2741E), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_tempRangeSwitch2, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_object_set_themeable_style_property(ui_tempRangeSwitch2, LV_PART_KNOB| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_graphBkg);
ui_object_set_themeable_style_property(ui_tempRangeSwitch2, LV_PART_KNOB| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_graphBkg);

ui_tempRangeHighLabel2 = lv_label_create(ui_uiTempRange2);
lv_obj_set_width( ui_tempRangeHighLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempRangeHighLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempRangeHighLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempRangeHighLabel2,"High");

ui_adjustThermostatContainer = lv_obj_create(ui_adjustThermostatScreen);
lv_obj_remove_style_all(ui_adjustThermostatContainer);
lv_obj_set_width( ui_adjustThermostatContainer, 432);
lv_obj_set_height( ui_adjustThermostatContainer, 297);
lv_obj_set_x( ui_adjustThermostatContainer, 0 );
lv_obj_set_y( ui_adjustThermostatContainer, 72 );
lv_obj_set_align( ui_adjustThermostatContainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_adjustThermostatContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_adjustThermostatContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_adjustThermostatContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_adjustThermostatContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_adjustThermostatContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_adjustThermostatContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_adjustThermostatContainer, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_adjustThermostatContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_uiThermostatPlaceholder3, ui_event_uiThermostatPlaceholder3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeatControls2, ui_event_HeatControls2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adjustThermostatContainer, ui_event_adjustThermostatContainer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adjustThermostatScreen, ui_event_adjustThermostatScreen, LV_EVENT_ALL, NULL);

}
