// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_Loading_Screen_screen_init(void)
{
ui_Loading_Screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Loading_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Loading_Screen, LV_SCROLLBAR_MODE_OFF);
lv_obj_add_event_cb(ui_Loading_Screen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Loading_Screen);
ui_object_set_themeable_style_property(ui_Loading_Screen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Loading_Screen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_border_color(ui_Loading_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Loading_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Loading_Screen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Loading_Screen, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Loading_Screen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Loading_Screen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Loading_Screen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Loading_Screen, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Loading_Screen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Loading_Screen, &ui_font_Open_Sans_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThermostatLoading = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_ThermostatLoading);
lv_obj_set_width( ui_ThermostatLoading, 200);
lv_obj_set_height( ui_ThermostatLoading, 110);
lv_obj_remove_flag( ui_ThermostatLoading, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ThermostatLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ThermostatLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_ThermostatLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_ThermostatLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_ThermostatLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_ThermostatLoading, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatControlsLoading = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_HeatControlsLoading);
lv_obj_set_width( ui_HeatControlsLoading, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_HeatControlsLoading, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_HeatControlsLoading, 0 );
lv_obj_set_y( ui_HeatControlsLoading, -134 );
lv_obj_set_align( ui_HeatControlsLoading, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_HeatControlsLoading,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HeatControlsLoading, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_HeatControlsLoading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeatControlsLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_HeatControlsLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_HeatControlsLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_HeatControlsLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_HeatControlsLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_HeatControlsLoading, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiHeatStateLoading = lv_obj_create(ui_HeatControlsLoading);
lv_obj_remove_style_all(ui_uiHeatStateLoading);
lv_obj_set_width( ui_uiHeatStateLoading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiHeatStateLoading, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_uiHeatStateLoading, 60 );
lv_obj_set_y( ui_uiHeatStateLoading, 63 );
lv_obj_set_align( ui_uiHeatStateLoading, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uiHeatStateLoading,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_uiHeatStateLoading, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_state( ui_uiHeatStateLoading, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_uiHeatStateLoading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_uiHeatStateLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiHeatStateLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
lv_obj_set_style_pad_left(ui_uiHeatStateLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiHeatStateLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiHeatStateLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiHeatStateLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_uiHeatStateLoading, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_uiHeatStateLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_uiHeatStateLoading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiHeatStateLoading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heatSwtichLabelLoading = lv_label_create(ui_uiHeatStateLoading);
lv_obj_set_width( ui_heatSwtichLabelLoading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heatSwtichLabelLoading, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_heatSwtichLabelLoading, LV_ALIGN_CENTER );
lv_label_set_text(ui_heatSwtichLabelLoading,"Heat");

ui_heatStateSwitchlLoading = lv_switch_create(ui_uiHeatStateLoading);
lv_obj_set_width( ui_heatStateSwitchlLoading, 50);
lv_obj_set_height( ui_heatStateSwitchlLoading, 25);
lv_obj_set_align( ui_heatStateSwitchlLoading, LV_ALIGN_CENTER );
lv_obj_add_state( ui_heatStateSwitchlLoading, LV_STATE_CHECKED );     /// States

lv_obj_set_style_bg_color(ui_heatStateSwitchlLoading, lv_color_hex(0x10AAF0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_heatStateSwitchlLoading, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_heatStateSwitchlLoading, lv_color_hex(0xA2741E), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_heatStateSwitchlLoading, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_object_set_themeable_style_property(ui_heatStateSwitchlLoading, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_graphBkg);
ui_object_set_themeable_style_property(ui_heatStateSwitchlLoading, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_graphBkg);

ui_uiTempRangelLoading = lv_obj_create(ui_HeatControlsLoading);
lv_obj_remove_style_all(ui_uiTempRangelLoading);
lv_obj_set_width( ui_uiTempRangelLoading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiTempRangelLoading, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_uiTempRangelLoading, 60 );
lv_obj_set_y( ui_uiTempRangelLoading, 63 );
lv_obj_set_align( ui_uiTempRangelLoading, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uiTempRangelLoading,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_uiTempRangelLoading, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_uiTempRangelLoading, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_uiTempRangelLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiTempRangelLoading, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
lv_obj_set_style_pad_left(ui_uiTempRangelLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiTempRangelLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiTempRangelLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiTempRangelLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_uiTempRangelLoading, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_uiTempRangelLoading, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_uiTempRangelLoading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiTempRangelLoading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tempRangeHighLabellLoading = lv_label_create(ui_uiTempRangelLoading);
lv_obj_set_width( ui_tempRangeHighLabellLoading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempRangeHighLabellLoading, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempRangeHighLabellLoading, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempRangeHighLabellLoading,"Low");

ui_tempRangeSwitchlLoading = lv_switch_create(ui_uiTempRangelLoading);
lv_obj_set_width( ui_tempRangeSwitchlLoading, 50);
lv_obj_set_height( ui_tempRangeSwitchlLoading, 25);
lv_obj_set_align( ui_tempRangeSwitchlLoading, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_tempRangeSwitchlLoading, lv_color_hex(0x10AAF0), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_tempRangeSwitchlLoading, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_tempRangeSwitchlLoading, lv_color_hex(0xA2741E), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_tempRangeSwitchlLoading, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_object_set_themeable_style_property(ui_tempRangeSwitchlLoading, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_graphBkg);
ui_object_set_themeable_style_property(ui_tempRangeSwitchlLoading, LV_PART_KNOB| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_graphBkg);

ui_tempRangeLowLabellLoading = lv_label_create(ui_uiTempRangelLoading);
lv_obj_set_width( ui_tempRangeLowLabellLoading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempRangeLowLabellLoading, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_tempRangeLowLabellLoading, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempRangeLowLabellLoading,"High");

ui_uiPumpLoading = ui_uiPump_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiPumpLoading, 0 );
lv_obj_set_y( ui_uiPumpLoading, -15 );
lv_obj_set_align( ui_uiPumpLoading, LV_ALIGN_LEFT_MID );



ui_uiPumpLoading2 = ui_uiPump_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiPumpLoading2, -27 );
lv_obj_set_y( ui_uiPumpLoading2, -16 );
lv_obj_set_align( ui_uiPumpLoading2, LV_ALIGN_CENTER );


lv_label_set_text(ui_comp_get_child(ui_uiPumpLoading2, UI_COMP_UIPUMP_LABEL),"Spa Pump 2");

ui_uiLightLoading = ui_uiLight_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiLightLoading, 101 );
lv_obj_set_y( ui_uiLightLoading, -14 );
lv_obj_set_align( ui_uiLightLoading, LV_ALIGN_CENTER );



ui_uiFilterLoading = ui_uiFilter_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiFilterLoading, 0 );
lv_obj_set_y( ui_uiFilterLoading, -15 );
lv_obj_set_align( ui_uiFilterLoading, LV_ALIGN_RIGHT_MID );



ui_uiTemperatureHistory2 = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_uiTemperatureHistory2);
lv_obj_set_width( ui_uiTemperatureHistory2, 220);
lv_obj_set_height( ui_uiTemperatureHistory2, 150);
lv_obj_set_align( ui_uiTemperatureHistory2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_remove_flag( ui_uiTemperatureHistory2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uiTemperatureHistory2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_uiTemperatureHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiTemperatureHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiTemperatureHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_uiTemperatureHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_uiTemperatureHistory2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_uiTemperatureHistory2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_uiTemperatureHistory2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiTemperatureHistory2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiTemperatureHistory2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiTemperatureHistory2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiTemperatureChart2 = lv_chart_create(ui_uiTemperatureHistory2);
lv_obj_set_width( ui_uiTemperatureChart2, 170);
lv_obj_set_height( ui_uiTemperatureChart2, 90);
lv_obj_set_x( ui_uiTemperatureChart2, 14 );
lv_obj_set_y( ui_uiTemperatureChart2, -4 );
lv_obj_set_align( ui_uiTemperatureChart2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_uiTemperatureChart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_uiTemperatureChart2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_uiTemperatureChart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_uiTemperatureChart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_uiTemperatureChart2, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_uiTemperatureChart2, 24);
lv_chart_set_range( ui_uiTemperatureChart2, LV_CHART_AXIS_PRIMARY_Y, 0, 4);
lv_chart_set_range( ui_uiTemperatureChart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_obj_set_style_bg_color(ui_uiTemperatureChart2, lv_color_hex(0xC3C3C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uiTemperatureChart2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiTemperatureChart2_Xaxis = lv_scale_create( ui_uiTemperatureChart2 );
lv_scale_set_mode( ui_uiTemperatureChart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_uiTemperatureChart2_Xaxis, lv_pct(100), 1 );
lv_obj_set_align( ui_uiTemperatureChart2_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_uiTemperatureChart2_Xaxis, 1 + lv_obj_get_style_pad_bottom(ui_uiTemperatureChart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_uiTemperatureChart2,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_uiTemperatureChart2_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_uiTemperatureChart2_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_uiTemperatureChart2_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_uiTemperatureChart2_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_uiTemperatureChart2_Xaxis, 2 >= 1 ? 2 : 1 );
ui_uiTemperatureChart2_Yaxis1 = lv_scale_create( ui_uiTemperatureChart2 );
lv_scale_set_mode( ui_uiTemperatureChart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_uiTemperatureChart2_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_uiTemperatureChart2_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_uiTemperatureChart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_uiTemperatureChart2,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_uiTemperatureChart2,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_uiTemperatureChart2_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_uiTemperatureChart2_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_uiTemperatureChart2_Yaxis1,  0, 4 );
lv_scale_set_total_tick_count( ui_uiTemperatureChart2_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_uiTemperatureChart2_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_uiTemperatureChart2_Yaxis2 = lv_scale_create( ui_uiTemperatureChart2 );
lv_scale_set_mode( ui_uiTemperatureChart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_uiTemperatureChart2_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_uiTemperatureChart2_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_uiTemperatureChart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_uiTemperatureChart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_uiTemperatureChart2,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_uiTemperatureChart2_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_uiTemperatureChart2_Yaxis2, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_uiTemperatureChart2_Yaxis2, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_uiTemperatureChart2_Yaxis2,  0, 0 );
lv_scale_set_total_tick_count( ui_uiTemperatureChart2_Yaxis2, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_uiTemperatureChart2_Yaxis2, 0 >= 1 ? 0 : 1 );
lv_scale_set_label_show( ui_uiTemperatureChart2_Yaxis2, false );
lv_chart_series_t* ui_uiTemperatureChart2_series_1 = lv_chart_add_series(ui_uiTemperatureChart2, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_uiTemperatureChart2_series_1_array[] = { 0,10,20,40,8,32,40,20,10,0,22,0,10,20,40,8,32,40,20,10,0,22,0,10,20,40,8,32,40,20,10,0,22,0,10,20,40,8,32,40,20,10,0,22 };
lv_chart_set_ext_y_array(ui_uiTemperatureChart2, ui_uiTemperatureChart2_series_1, ui_uiTemperatureChart2_series_1_array);


lv_obj_set_style_text_font(ui_uiTemperatureChart2_Xaxis, &ui_font_Open_Sans_Bold_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiTemperatureChart2_Yaxis1, &ui_font_Open_Sans_Bold_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiTemperatureChart2_Yaxis2, &ui_font_Open_Sans_Bold_12, LV_PART_MAIN| LV_STATE_DEFAULT);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_uiTemperatureChart2, LV_MAX3(1, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_uiTemperatureChart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_temperatureChartLabel2 = lv_label_create(ui_uiTemperatureHistory2);
lv_obj_set_height( ui_temperatureChartLabel2, 30);
lv_obj_set_width( ui_temperatureChartLabel2, LV_SIZE_CONTENT);  /// 142
lv_obj_set_x( ui_temperatureChartLabel2, 2 );
lv_obj_set_y( ui_temperatureChartLabel2, 7 );
lv_obj_set_align( ui_temperatureChartLabel2, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_temperatureChartLabel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_temperatureChartLabel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_temperatureChartLabel2,"Temperature °C");
lv_obj_set_style_pad_left(ui_temperatureChartLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_temperatureChartLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_temperatureChartLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_temperatureChartLabel2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiHeaterHistory2 = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_uiHeaterHistory2);
lv_obj_set_width( ui_uiHeaterHistory2, 220);
lv_obj_set_height( ui_uiHeaterHistory2, 150);
lv_obj_set_align( ui_uiHeaterHistory2, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_remove_flag( ui_uiHeaterHistory2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uiHeaterHistory2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_uiHeaterHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiHeaterHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiHeaterHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_uiHeaterHistory2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_uiHeaterHistory2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_uiHeaterHistory2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_uiHeaterHistory2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiHeaterHistory2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiHeaterHistory2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiHeaterHistory2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiHeaterChart2 = lv_chart_create(ui_uiHeaterHistory2);
lv_obj_set_width( ui_uiHeaterChart2, 170);
lv_obj_set_height( ui_uiHeaterChart2, 90);
lv_obj_set_x( ui_uiHeaterChart2, 15 );
lv_obj_set_y( ui_uiHeaterChart2, -4 );
lv_obj_set_align( ui_uiHeaterChart2, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_uiHeaterChart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_uiHeaterChart2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_uiHeaterChart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_uiHeaterChart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_uiHeaterChart2, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_uiHeaterChart2, 24);
lv_chart_set_range( ui_uiHeaterChart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
ui_object_set_themeable_style_property(ui_uiHeaterChart2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_graphBkg);
ui_object_set_themeable_style_property(ui_uiHeaterChart2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_graphBkg);

ui_uiHeaterChart2_Xaxis = lv_scale_create( ui_uiHeaterChart2 );
lv_scale_set_mode( ui_uiHeaterChart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_uiHeaterChart2_Xaxis, lv_pct(100), 1 );
lv_obj_set_align( ui_uiHeaterChart2_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_uiHeaterChart2_Xaxis, 1 + lv_obj_get_style_pad_bottom(ui_uiHeaterChart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_uiHeaterChart2,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_uiHeaterChart2_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_uiHeaterChart2_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_uiHeaterChart2_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_uiHeaterChart2_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_uiHeaterChart2_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_uiHeaterChart2_Xaxis, 2 >= 1 ? 2 : 1 );
ui_uiHeaterChart2_Yaxis1 = lv_scale_create( ui_uiHeaterChart2 );
lv_scale_set_mode( ui_uiHeaterChart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_uiHeaterChart2_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_uiHeaterChart2_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_uiHeaterChart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_uiHeaterChart2,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_uiHeaterChart2,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_uiHeaterChart2_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_uiHeaterChart2_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_uiHeaterChart2_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_uiHeaterChart2_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_uiHeaterChart2_Yaxis2 = lv_scale_create( ui_uiHeaterChart2 );
lv_scale_set_mode( ui_uiHeaterChart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_uiHeaterChart2_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_uiHeaterChart2_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_uiHeaterChart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_uiHeaterChart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_uiHeaterChart2,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_uiHeaterChart2_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_uiHeaterChart2_Yaxis2, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_uiHeaterChart2_Yaxis2, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_range( ui_uiHeaterChart2_Yaxis2,  0, 0 );
lv_scale_set_total_tick_count( ui_uiHeaterChart2_Yaxis2, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_uiHeaterChart2_Yaxis2, 0 >= 1 ? 0 : 1 );
lv_scale_set_label_show( ui_uiHeaterChart2_Yaxis2, false );
lv_chart_series_t* ui_uiHeaterChart2_series_1 = lv_chart_add_series(ui_uiHeaterChart2, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_uiHeaterChart2_series_1_array[] = { 0,10,20,40,8,32,40,20,10,0,22,0,10,20,40,8,32,40,20,10,0,22,0,10,20,40,8,32,40,20,10,0,22 };
lv_chart_set_ext_y_array(ui_uiHeaterChart2, ui_uiHeaterChart2_series_1, ui_uiHeaterChart2_series_1_array);


lv_obj_set_style_text_font(ui_uiHeaterChart2_Xaxis, &ui_font_Open_Sans_Bold_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiHeaterChart2_Yaxis1, &ui_font_Open_Sans_Bold_12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiHeaterChart2_Yaxis2, &ui_font_Open_Sans_Bold_12, LV_PART_MAIN| LV_STATE_DEFAULT);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_uiHeaterChart2, LV_MAX3(1, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_uiHeaterChart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_heaterChartLabel2 = lv_label_create(ui_uiHeaterHistory2);
lv_obj_set_height( ui_heaterChartLabel2, 30);
lv_obj_set_width( ui_heaterChartLabel2, LV_SIZE_CONTENT);  /// 142
lv_obj_set_x( ui_heaterChartLabel2, 2 );
lv_obj_set_y( ui_heaterChartLabel2, 7 );
lv_obj_set_align( ui_heaterChartLabel2, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_heaterChartLabel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_heaterChartLabel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_heaterChartLabel2,"Heater (Min)");
lv_obj_set_style_pad_left(ui_heaterChartLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_heaterChartLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_heaterChartLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_heaterChartLabel2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiClock2 = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_uiClock2);
lv_obj_set_width( ui_uiClock2, LV_SIZE_CONTENT);  /// 250
lv_obj_set_height( ui_uiClock2, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_uiClock2, LV_ALIGN_TOP_RIGHT );
lv_obj_remove_flag( ui_uiClock2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uiClock2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_uiClock2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiClock2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_uiClock2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_uiClock2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_uiClock2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_uiClock2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiClock2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiClock2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiClock2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_uiClock2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiClockLabel2 = lv_label_create(ui_uiClock2);
lv_obj_set_width( ui_uiClockLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiClockLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_uiClockLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiClockLabel2,"Loading Please Wait");
lv_obj_set_style_pad_left(ui_uiClockLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uiClockLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uiClockLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uiClockLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_uiClockLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_uiClockLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 100);
lv_obj_set_height( ui_Container1, 50);
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_ThermostatLoading, ui_event_ThermostatLoading, LV_EVENT_ALL, NULL);

}
