// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_settingsAndAbout_screen_init(void)
{
ui_settingsAndAbout = lv_obj_create(NULL);
lv_obj_remove_flag( ui_settingsAndAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_settingsAndAbout);
lv_tabview_set_tab_bar_size(ui_TabView1,50);
lv_obj_set_width( ui_TabView1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TabView1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TabView1, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView1), &ui_font_Open_Sans_Bold_24,  LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_TabView1),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x980E0E),  LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView1), lv_color_hex(0x980E0E),  LV_PART_MAIN | LV_STATE_EDITED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_EDITED);

ui_settingsPage = lv_tabview_add_tab(ui_TabView1, "Settings");
lv_obj_set_flex_flow(ui_settingsPage,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_settingsPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_settingsContariner = lv_obj_create(ui_settingsPage);
lv_obj_remove_style_all(ui_settingsContariner);
lv_obj_set_width( ui_settingsContariner, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingsContariner, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_settingsContariner, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_settingsContariner, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_settingsContariner, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_settingsContariner, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_brightnessContainer3 = lv_obj_create(ui_settingsContariner);
lv_obj_remove_style_all(ui_brightnessContainer3);
lv_obj_set_width( ui_brightnessContainer3, 120);
lv_obj_set_height( ui_brightnessContainer3, 200);
lv_obj_set_x( ui_brightnessContainer3, -23 );
lv_obj_set_y( ui_brightnessContainer3, -54 );
lv_obj_set_align( ui_brightnessContainer3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_brightnessContainer3,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_brightnessContainer3, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
lv_obj_remove_flag( ui_brightnessContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_brightnessContainer3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_brightnessContainer3, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessSlider3 = lv_slider_create(ui_brightnessContainer3);
lv_slider_set_value( ui_brightnessSlider3, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_brightnessSlider3)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_brightnessSlider3, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_brightnessSlider3, 20);
lv_obj_set_height( ui_brightnessSlider3, 150);
lv_obj_set_x( ui_brightnessSlider3, 61 );
lv_obj_set_y( ui_brightnessSlider3, 42 );
lv_obj_set_align( ui_brightnessSlider3, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(ui_brightnessSlider3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_brightnessSlider3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
lv_obj_set_style_bg_color(ui_brightnessSlider3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_brightnessSlider3, 255, LV_PART_MAIN| LV_STATE_CHECKED);


//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_brightnessSlider3,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_brightnessSlider3, lv_obj_get_style_pad_right(ui_brightnessSlider3,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_brightnessLabel3 = lv_label_create(ui_brightnessContainer3);
lv_obj_set_width( ui_brightnessLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightnessLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightnessLabel3, -117 );
lv_obj_set_y( ui_brightnessLabel3, 152 );
lv_obj_set_align( ui_brightnessLabel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_brightnessLabel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_brightnessLabel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_brightnessLabel3,"Brightness");
ui_object_set_themeable_style_property(ui_brightnessLabel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_graphBkg);
ui_object_set_themeable_style_property(ui_brightnessLabel3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_graphBkg);
lv_obj_set_style_text_font(ui_brightnessLabel3, &ui_font_Open_Sans_Bold_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Checkbox2 = lv_checkbox_create(ui_settingsContariner);
lv_checkbox_set_text(ui_Checkbox2,"Checkbox");
lv_obj_set_width( ui_Checkbox2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Checkbox2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_aboutPage = lv_tabview_add_tab(ui_TabView1, "About");
lv_obj_set_flex_flow(ui_aboutPage,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_aboutPage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Container9 = lv_obj_create(ui_aboutPage);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 100);
lv_obj_set_height( ui_Container9, 50);
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Container9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Container9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_aboutLabel = lv_label_create(ui_Container9);
lv_obj_set_width( ui_aboutLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aboutLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aboutLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_aboutLabel,"This is the About Test");
lv_obj_set_style_text_font(ui_aboutLabel, &ui_font_Open_Sans_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_settingsAndAbout, ui_event_settingsAndAbout, LV_EVENT_ALL, NULL);

}
