// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_Filter_Samples_screen_init(void)
{
ui_Filter_Samples = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Filter_Samples, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Filter_Samples, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_flex_flow(ui_Filter_Samples,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Filter_Samples, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Filter_Samples, lv_color_hex(0xBFE0F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Filter_Samples, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Filter_Samples, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Filter_Samples, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Filter_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Filter_Samples, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Filter_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Filter_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Filter_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Filter_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Filter_Samples, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Filter_Samples, &ui_font_Montserrat_Bold_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Off_Sample1 = lv_obj_create(ui_Filter_Samples);
lv_obj_remove_style_all(ui_Off_Sample1);
lv_obj_set_width( ui_Off_Sample1, 480);
lv_obj_set_height( ui_Off_Sample1, 140);
lv_obj_set_x( ui_Off_Sample1, -161 );
lv_obj_set_y( ui_Off_Sample1, 137 );
lv_obj_set_align( ui_Off_Sample1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Off_Sample1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Off_Sample1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Off_Sample1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Off_Sample1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Off_Sample1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Off_Sample1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label1,"Off");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pump_Off1 = lv_obj_create(ui_Off_Sample1);
lv_obj_remove_style_all(ui_Pump_Off1);
lv_obj_set_width( ui_Pump_Off1, 60);
lv_obj_set_height( ui_Pump_Off1, 140);
lv_obj_set_x( ui_Pump_Off1, 60 );
lv_obj_set_y( ui_Pump_Off1, 63 );
lv_obj_set_align( ui_Pump_Off1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Pump_Off1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Pump_Off1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Pump_Off1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Pump_Off1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pump_Off1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pump_Off1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pump_Off1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Pump_Off1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Pump_Off1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Pump_Off1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Pump_Off1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Pump_Off1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pump_Off1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpButton1 = lv_imagebutton_create(ui_Pump_Off1);
lv_imagebutton_set_src(ui_pumpButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_filteron_png, NULL);
lv_imagebutton_set_src(ui_pumpButton1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton1, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton1, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton1, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpButton1, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpButton1, 100);
lv_obj_set_width( ui_pumpButton1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpButton1, 82 );
lv_obj_set_y( ui_pumpButton1, 20 );
lv_obj_set_align( ui_pumpButton1, LV_ALIGN_CENTER );

ui_pumpLabel2 = lv_label_create(ui_Pump_Off1);
lv_obj_set_width( ui_pumpLabel2, 100);
lv_obj_set_height( ui_pumpLabel2, 30);
lv_obj_set_x( ui_pumpLabel2, 41 );
lv_obj_set_y( ui_pumpLabel2, 47 );
lv_obj_set_align( ui_pumpLabel2, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_pumpLabel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_pumpLabel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_pumpLabel2,"Filter");
lv_obj_set_style_pad_left(ui_pumpLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pumpLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pumpLabel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pumpLabel2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pump_Off8 = lv_obj_create(ui_Off_Sample1);
lv_obj_remove_style_all(ui_Pump_Off8);
lv_obj_set_width( ui_Pump_Off8, 60);
lv_obj_set_height( ui_Pump_Off8, 140);
lv_obj_set_x( ui_Pump_Off8, 60 );
lv_obj_set_y( ui_Pump_Off8, 63 );
lv_obj_set_align( ui_Pump_Off8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Pump_Off8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Pump_Off8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Pump_Off8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Pump_Off8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pump_Off8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pump_Off8, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pump_Off8, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Pump_Off8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Pump_Off8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Pump_Off8, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Pump_Off8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Pump_Off8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pump_Off8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpButton11 = lv_imagebutton_create(ui_Pump_Off8);
lv_imagebutton_set_src(ui_pumpButton11, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_filteron_png, NULL);
lv_imagebutton_set_src(ui_pumpButton11, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton11, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton11, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton11, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpButton11, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpButton11, 100);
lv_obj_set_width( ui_pumpButton11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpButton11, 82 );
lv_obj_set_y( ui_pumpButton11, 20 );
lv_obj_set_align( ui_pumpButton11, LV_ALIGN_CENTER );

ui_pumpLabel12 = lv_label_create(ui_Pump_Off8);
lv_obj_set_width( ui_pumpLabel12, 100);
lv_obj_set_height( ui_pumpLabel12, 30);
lv_obj_set_x( ui_pumpLabel12, 41 );
lv_obj_set_y( ui_pumpLabel12, 47 );
lv_obj_set_align( ui_pumpLabel12, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_pumpLabel12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_pumpLabel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_pumpLabel12,"Filter");
lv_obj_set_style_pad_left(ui_pumpLabel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pumpLabel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pumpLabel12, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pumpLabel12, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_High_Sample1 = lv_obj_create(ui_Filter_Samples);
lv_obj_remove_style_all(ui_High_Sample1);
lv_obj_set_width( ui_High_Sample1, 480);
lv_obj_set_height( ui_High_Sample1, 140);
lv_obj_set_x( ui_High_Sample1, -161 );
lv_obj_set_y( ui_High_Sample1, 137 );
lv_obj_set_align( ui_High_Sample1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_High_Sample1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_High_Sample1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_High_Sample1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_High_Sample1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_High_Sample1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_High_Sample1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label11,"On");
lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label11, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Filter_On = lv_obj_create(ui_High_Sample1);
lv_obj_remove_style_all(ui_Filter_On);
lv_obj_set_width( ui_Filter_On, 60);
lv_obj_set_height( ui_Filter_On, 140);
lv_obj_set_x( ui_Filter_On, 60 );
lv_obj_set_y( ui_Filter_On, 63 );
lv_obj_set_align( ui_Filter_On, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Filter_On,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Filter_On, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Filter_On, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Filter_On, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Filter_On, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Filter_On, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Filter_On, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Filter_On, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Filter_On, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Filter_On, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Filter_On, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Filter_On, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Filter_On, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Filter_On, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Filter_On, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpButton3 = lv_imagebutton_create(ui_Filter_On);
lv_imagebutton_set_src(ui_pumpButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_filteron_png, NULL);
lv_imagebutton_set_src(ui_pumpButton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton3, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton3, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton3, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpButton3, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpButton3, 100);
lv_obj_set_width( ui_pumpButton3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpButton3, 82 );
lv_obj_set_y( ui_pumpButton3, 20 );
lv_obj_set_align( ui_pumpButton3, LV_ALIGN_CENTER );

ui_pumpLabel5 = lv_label_create(ui_Filter_On);
lv_obj_set_width( ui_pumpLabel5, 100);
lv_obj_set_height( ui_pumpLabel5, 30);
lv_obj_set_x( ui_pumpLabel5, 41 );
lv_obj_set_y( ui_pumpLabel5, 47 );
lv_obj_set_align( ui_pumpLabel5, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_pumpLabel5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_pumpLabel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_pumpLabel5,"Filter");
lv_obj_set_style_pad_left(ui_pumpLabel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pumpLabel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pumpLabel5, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pumpLabel5, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

}
