// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_Light_Samples_screen_init(void)
{
ui_Light_Samples = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Light_Samples, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Light_Samples,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Light_Samples, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Light_Samples, lv_color_hex(0xBFE0F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Light_Samples, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Light_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Light_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Light_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Light_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Light_Samples, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Light_Samples, &ui_font_Montserrat_Bold_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OffSample = lv_obj_create(ui_Light_Samples);
lv_obj_remove_style_all(ui_OffSample);
lv_obj_set_width( ui_OffSample, 480);
lv_obj_set_height( ui_OffSample, 130);
lv_obj_set_x( ui_OffSample, -161 );
lv_obj_set_y( ui_OffSample, 137 );
lv_obj_set_align( ui_OffSample, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_OffSample,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_OffSample, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_OffSample, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_OffSample, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_OffSample, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_OffSample);
lv_obj_set_width( ui_Label6, 180);
lv_obj_set_height( ui_Label6, 100);
lv_obj_set_align( ui_Label6, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label6,"\n\nOff");
lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label6, lv_color_hex(0x5051F2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp8 = lv_obj_create(ui_OffSample);
lv_obj_remove_style_all(ui_Lamp8);
lv_obj_set_width( ui_Lamp8, 104);
lv_obj_set_height( ui_Lamp8, 130);
lv_obj_set_x( ui_Lamp8, 60 );
lv_obj_set_y( ui_Lamp8, 63 );
lv_obj_set_align( ui_Lamp8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Lamp8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp8, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp8, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton8 = lv_imagebutton_create(ui_Lamp8);
lv_imagebutton_set_src(ui_lampButton8, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_lightoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton8, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton8, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton8, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton8, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_lightoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton8, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton8, 100);
lv_obj_set_width( ui_lampButton8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton8, 82 );
lv_obj_set_y( ui_lampButton8, 20 );
lv_obj_set_align( ui_lampButton8, LV_ALIGN_CENTER );

ui_lampLabel5 = lv_label_create(ui_Lamp8);
lv_obj_set_width( ui_lampLabel5, 100);
lv_obj_set_height( ui_lampLabel5, 30);
lv_obj_set_x( ui_lampLabel5, 41 );
lv_obj_set_y( ui_lampLabel5, 47 );
lv_obj_set_align( ui_lampLabel5, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_lampLabel5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_lampLabel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_lampLabel5,"Spa Light 1");
lv_obj_set_style_pad_left(ui_lampLabel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lampLabel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lampLabel5, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lampLabel5, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp2 = lv_obj_create(ui_OffSample);
lv_obj_remove_style_all(ui_Lamp2);
lv_obj_set_width( ui_Lamp2, 104);
lv_obj_set_height( ui_Lamp2, 108);
lv_obj_set_x( ui_Lamp2, 60 );
lv_obj_set_y( ui_Lamp2, 63 );
lv_obj_set_align( ui_Lamp2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Lamp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton2 = lv_imagebutton_create(ui_Lamp2);
lv_imagebutton_set_src(ui_lampButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_lightoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton2, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_lighton_png, NULL);
lv_imagebutton_set_src(ui_lampButton2, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton2, 100);
lv_obj_set_width( ui_lampButton2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton2, 82 );
lv_obj_set_y( ui_lampButton2, 20 );
lv_obj_set_align( ui_lampButton2, LV_ALIGN_CENTER );

ui_Container2 = lv_obj_create(ui_Light_Samples);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 480);
lv_obj_set_height( ui_Container2, 130);
lv_obj_set_x( ui_Container2, -161 );
lv_obj_set_y( ui_Container2, 137 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label5, 180);
lv_obj_set_height( ui_Label5, 100);
lv_obj_set_align( ui_Label5, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label5,"\n\nOn");
lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp5 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Lamp5);
lv_obj_set_width( ui_Lamp5, 104);
lv_obj_set_height( ui_Lamp5, 130);
lv_obj_set_x( ui_Lamp5, 60 );
lv_obj_set_y( ui_Lamp5, 63 );
lv_obj_set_align( ui_Lamp5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Lamp5, lv_color_hex(0xE2F00C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Lamp5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Lamp5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp5, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp5, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton5 = lv_imagebutton_create(ui_Lamp5);
lv_imagebutton_set_src(ui_lampButton5, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_lightoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton5, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton5, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton5, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton5, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_lightoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton5, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton5, 100);
lv_obj_set_width( ui_lampButton5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton5, 82 );
lv_obj_set_y( ui_lampButton5, 20 );
lv_obj_set_align( ui_lampButton5, LV_ALIGN_CENTER );

ui_lampLabel4 = lv_label_create(ui_Lamp5);
lv_obj_set_width( ui_lampLabel4, 100);
lv_obj_set_height( ui_lampLabel4, 30);
lv_obj_set_x( ui_lampLabel4, 41 );
lv_obj_set_y( ui_lampLabel4, 47 );
lv_obj_set_align( ui_lampLabel4, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_lampLabel4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_lampLabel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_lampLabel4,"Spa Light 1");
lv_obj_set_style_pad_left(ui_lampLabel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lampLabel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lampLabel4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lampLabel4, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp6 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Lamp6);
lv_obj_set_width( ui_Lamp6, 104);
lv_obj_set_height( ui_Lamp6, 108);
lv_obj_set_x( ui_Lamp6, 60 );
lv_obj_set_y( ui_Lamp6, 63 );
lv_obj_set_align( ui_Lamp6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Lamp6, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Lamp6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Lamp6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp6, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp6, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton6 = lv_imagebutton_create(ui_Lamp6);
lv_imagebutton_set_src(ui_lampButton6, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_lightoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton6, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton6, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton6, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton6, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_lighton_png, NULL);
lv_imagebutton_set_src(ui_lampButton6, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton6, 100);
lv_obj_set_width( ui_lampButton6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton6, 82 );
lv_obj_set_y( ui_lampButton6, 20 );
lv_obj_set_align( ui_lampButton6, LV_ALIGN_CENTER );

ui_Container5 = lv_obj_create(ui_Light_Samples);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 480);
lv_obj_set_height( ui_Container5, 130);
lv_obj_set_x( ui_Container5, -161 );
lv_obj_set_y( ui_Container5, 137 );
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container5, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label3, 180);
lv_obj_set_height( ui_Label3, 100);
lv_obj_set_align( ui_Label3, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label3,"\n\nOn");
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Sample_Spa_Light_1 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Sample_Spa_Light_1);
lv_obj_set_width( ui_Sample_Spa_Light_1, 104);
lv_obj_set_height( ui_Sample_Spa_Light_1, 130);
lv_obj_set_x( ui_Sample_Spa_Light_1, 60 );
lv_obj_set_y( ui_Sample_Spa_Light_1, 63 );
lv_obj_set_align( ui_Sample_Spa_Light_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Sample_Spa_Light_1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Sample_Spa_Light_1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Sample_Spa_Light_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Sample_Spa_Light_1, lv_color_hex(0x0CF044), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Sample_Spa_Light_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Sample_Spa_Light_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Sample_Spa_Light_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Sample_Spa_Light_1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Sample_Spa_Light_1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Sample_Spa_Light_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Sample_Spa_Light_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spa_Light_Image = lv_imagebutton_create(ui_Sample_Spa_Light_1);
lv_imagebutton_set_src(ui_Spa_Light_Image, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_lighton_png, NULL);
lv_imagebutton_set_src(ui_Spa_Light_Image, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_Spa_Light_Image, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_Spa_Light_Image, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_Spa_Light_Image, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_lighton_png, NULL);
lv_imagebutton_set_src(ui_Spa_Light_Image, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_Spa_Light_Image, 100);
lv_obj_set_width( ui_Spa_Light_Image, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Spa_Light_Image, 82 );
lv_obj_set_y( ui_Spa_Light_Image, 20 );
lv_obj_set_align( ui_Spa_Light_Image, LV_ALIGN_CENTER );

ui_Spa_Ligtht_Label = lv_label_create(ui_Sample_Spa_Light_1);
lv_obj_set_width( ui_Spa_Ligtht_Label, 100);
lv_obj_set_height( ui_Spa_Ligtht_Label, 30);
lv_obj_set_x( ui_Spa_Ligtht_Label, 41 );
lv_obj_set_y( ui_Spa_Ligtht_Label, 47 );
lv_obj_set_align( ui_Spa_Ligtht_Label, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_Spa_Ligtht_Label,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Spa_Ligtht_Label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Spa_Ligtht_Label,"Spa Light 1");
lv_obj_set_style_pad_left(ui_Spa_Ligtht_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Spa_Ligtht_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Spa_Ligtht_Label, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Spa_Ligtht_Label, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp3 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Lamp3);
lv_obj_set_width( ui_Lamp3, 104);
lv_obj_set_height( ui_Lamp3, 108);
lv_obj_set_x( ui_Lamp3, 60 );
lv_obj_set_y( ui_Lamp3, 63 );
lv_obj_set_align( ui_Lamp3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Lamp3, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Lamp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Lamp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp3, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton3 = lv_imagebutton_create(ui_Lamp3);
lv_imagebutton_set_src(ui_lampButton3, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_lighton_png, NULL);
lv_imagebutton_set_src(ui_lampButton3, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton3, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton3, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton3, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_lighton_png, NULL);
lv_imagebutton_set_src(ui_lampButton3, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton3, 100);
lv_obj_set_width( ui_lampButton3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton3, 82 );
lv_obj_set_y( ui_lampButton3, 20 );
lv_obj_set_align( ui_lampButton3, LV_ALIGN_CENTER );

}
