// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_Loading_Screen_screen_init(void)
{
ui_Loading_Screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Loading_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Loading_Screen, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_flex_flow(ui_Loading_Screen,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Loading_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
ui_object_set_themeable_style_property(ui_Loading_Screen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Loading_Screen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_border_color(ui_Loading_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Loading_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Loading_Screen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Loading_Screen, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Loading_Screen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Loading_Screen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Loading_Screen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Loading_Screen, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Loading_Screen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Loading_Screen, &ui_font_Open_Sans_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoadingContainer = lv_obj_create(ui_Loading_Screen);
lv_obj_remove_style_all(ui_LoadingContainer);
lv_obj_set_width( ui_LoadingContainer, 250);
lv_obj_set_height( ui_LoadingContainer, 200);
lv_obj_set_x( ui_LoadingContainer, -122 );
lv_obj_set_y( ui_LoadingContainer, 146 );
lv_obj_set_align( ui_LoadingContainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_LoadingContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_LoadingContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_LoadingContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_AccessoryOffBkg);
ui_object_set_themeable_style_property(ui_LoadingContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_widgetBorder);
ui_object_set_themeable_style_property(ui_LoadingContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_widgetBorder);
lv_obj_set_style_border_width(ui_LoadingContainer, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoadingLabel = lv_label_create(ui_LoadingContainer);
lv_obj_set_width( ui_LoadingLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LoadingLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LoadingLabel,"Loading please Wait");
lv_obj_set_style_text_font(ui_LoadingLabel, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiPumpLoading = ui_uiPump_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiPumpLoading, 60 );
lv_obj_set_y( ui_uiPumpLoading, 63 );



ui_uiFilterLoading = ui_uiFilter_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiFilterLoading, 60 );
lv_obj_set_y( ui_uiFilterLoading, 63 );



ui_uiLightLoading = ui_uiLight_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiLightLoading, 60 );
lv_obj_set_y( ui_uiLightLoading, 63 );



ui_uiLight2 = ui_uiLight_create(ui_Loading_Screen);
lv_obj_set_x( ui_uiLight2, 60 );
lv_obj_set_y( ui_uiLight2, 63 );



}
