// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_Pump_Samples_screen_init(void)
{
ui_Pump_Samples = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Pump_Samples, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Pump_Samples, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_flex_flow(ui_Pump_Samples,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Pump_Samples, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Pump_Samples, lv_color_hex(0xBFE0F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pump_Samples, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pump_Samples, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pump_Samples, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pump_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pump_Samples, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Pump_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Pump_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Pump_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Pump_Samples, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Pump_Samples, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Pump_Samples, &ui_font_Montserrat_Bold_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Off_Sample = lv_obj_create(ui_Pump_Samples);
lv_obj_remove_style_all(ui_Off_Sample);
lv_obj_set_width( ui_Off_Sample, 480);
lv_obj_set_height( ui_Off_Sample, 130);
lv_obj_set_x( ui_Off_Sample, -161 );
lv_obj_set_y( ui_Off_Sample, 137 );
lv_obj_set_align( ui_Off_Sample, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Off_Sample,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Off_Sample, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Off_Sample, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Off_Sample, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Off_Sample, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Off_Sample);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label9,"Off");
lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label9, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pump_Off = lv_obj_create(ui_Off_Sample);
lv_obj_remove_style_all(ui_Pump_Off);
lv_obj_set_width( ui_Pump_Off, 110);
lv_obj_set_height( ui_Pump_Off, 130);
lv_obj_set_x( ui_Pump_Off, 60 );
lv_obj_set_y( ui_Pump_Off, 63 );
lv_obj_set_align( ui_Pump_Off, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Pump_Off,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Pump_Off, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Pump_Off, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Pump_Off, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pump_Off, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pump_Off, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pump_Off, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Pump_Off, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pump_Off, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpButton7 = lv_imagebutton_create(ui_Pump_Off);
lv_imagebutton_set_src(ui_pumpButton7, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpButton7, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton7, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton7, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton7, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpButton7, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpButton7, 100);
lv_obj_set_width( ui_pumpButton7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpButton7, 82 );
lv_obj_set_y( ui_pumpButton7, 20 );
lv_obj_set_align( ui_pumpButton7, LV_ALIGN_CENTER );

ui_pumpLabel7 = lv_label_create(ui_Pump_Off);
lv_obj_set_width( ui_pumpLabel7, 100);
lv_obj_set_height( ui_pumpLabel7, 30);
lv_obj_set_x( ui_pumpLabel7, 41 );
lv_obj_set_y( ui_pumpLabel7, 47 );
lv_obj_set_align( ui_pumpLabel7, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_pumpLabel7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_pumpLabel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_pumpLabel7,"Spa Pump 1");
lv_obj_set_style_pad_left(ui_pumpLabel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pumpLabel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pumpLabel7, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pumpLabel7, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp1 = lv_obj_create(ui_Off_Sample);
lv_obj_remove_style_all(ui_Lamp1);
lv_obj_set_width( ui_Lamp1, 104);
lv_obj_set_height( ui_Lamp1, 108);
lv_obj_set_x( ui_Lamp1, 60 );
lv_obj_set_y( ui_Lamp1, 63 );
lv_obj_set_align( ui_Lamp1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Lamp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpLabel = lv_imagebutton_create(ui_Lamp1);
lv_imagebutton_set_src(ui_pumpLabel, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpLabel, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpLabel, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpLabel, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpLabel, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpLabel, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpLabel, 100);
lv_obj_set_width( ui_pumpLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpLabel, 82 );
lv_obj_set_y( ui_pumpLabel, 20 );
lv_obj_set_align( ui_pumpLabel, LV_ALIGN_CENTER );

ui_Low_Sample = lv_obj_create(ui_Pump_Samples);
lv_obj_remove_style_all(ui_Low_Sample);
lv_obj_set_width( ui_Low_Sample, 480);
lv_obj_set_height( ui_Low_Sample, 130);
lv_obj_set_x( ui_Low_Sample, -161 );
lv_obj_set_y( ui_Low_Sample, 137 );
lv_obj_set_align( ui_Low_Sample, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Low_Sample,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Low_Sample, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Low_Sample, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Low_Sample, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Low_Sample, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Low_Sample);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label7,"low");
lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pump_Off2 = lv_obj_create(ui_Low_Sample);
lv_obj_remove_style_all(ui_Pump_Off2);
lv_obj_set_width( ui_Pump_Off2, 110);
lv_obj_set_height( ui_Pump_Off2, 130);
lv_obj_set_x( ui_Pump_Off2, 60 );
lv_obj_set_y( ui_Pump_Off2, 63 );
lv_obj_set_align( ui_Pump_Off2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Pump_Off2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Pump_Off2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Pump_Off2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pump_Off2, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pump_Off2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pump_Off2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pump_Off2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pump_Off2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pump_Off2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Pump_Off2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pump_Off2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton10 = lv_imagebutton_create(ui_Pump_Off2);
lv_imagebutton_set_src(ui_lampButton10, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pumplow_png, NULL);
lv_imagebutton_set_src(ui_lampButton10, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton10, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton10, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton10, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton10, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton10, 100);
lv_obj_set_width( ui_lampButton10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton10, 82 );
lv_obj_set_y( ui_lampButton10, 20 );
lv_obj_set_align( ui_lampButton10, LV_ALIGN_CENTER );

ui_lampLabel3 = lv_label_create(ui_Pump_Off2);
lv_obj_set_width( ui_lampLabel3, 100);
lv_obj_set_height( ui_lampLabel3, 30);
lv_obj_set_x( ui_lampLabel3, 41 );
lv_obj_set_y( ui_lampLabel3, 47 );
lv_obj_set_align( ui_lampLabel3, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_lampLabel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_lampLabel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_lampLabel3,"Spa Pump 1");
lv_obj_set_style_pad_left(ui_lampLabel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lampLabel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lampLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lampLabel3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp7 = lv_obj_create(ui_Low_Sample);
lv_obj_remove_style_all(ui_Lamp7);
lv_obj_set_width( ui_Lamp7, 104);
lv_obj_set_height( ui_Lamp7, 108);
lv_obj_set_x( ui_Lamp7, 60 );
lv_obj_set_y( ui_Lamp7, 63 );
lv_obj_set_align( ui_Lamp7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp7,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Lamp7, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Lamp7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Lamp7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp7, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp7, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lampButton4 = lv_imagebutton_create(ui_Lamp7);
lv_imagebutton_set_src(ui_lampButton4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pumplow_png, NULL);
lv_imagebutton_set_src(ui_lampButton4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton4, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton4, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_lampButton4, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_lampButton4, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_lampButton4, 100);
lv_obj_set_width( ui_lampButton4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lampButton4, 82 );
lv_obj_set_y( ui_lampButton4, 20 );
lv_obj_set_align( ui_lampButton4, LV_ALIGN_CENTER );

ui_High_Sample = lv_obj_create(ui_Pump_Samples);
lv_obj_remove_style_all(ui_High_Sample);
lv_obj_set_width( ui_High_Sample, 480);
lv_obj_set_height( ui_High_Sample, 130);
lv_obj_set_x( ui_High_Sample, -161 );
lv_obj_set_y( ui_High_Sample, 137 );
lv_obj_set_align( ui_High_Sample, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_High_Sample,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_High_Sample, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_High_Sample, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_High_Sample, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_High_Sample, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_High_Sample);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label8,"Off");
lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &ui_font_Montserrat_Bold_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label8, lv_color_hex(0xF7F7FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Pump_Off3 = lv_obj_create(ui_High_Sample);
lv_obj_remove_style_all(ui_Pump_Off3);
lv_obj_set_width( ui_Pump_Off3, 110);
lv_obj_set_height( ui_Pump_Off3, 130);
lv_obj_set_x( ui_Pump_Off3, 60 );
lv_obj_set_y( ui_Pump_Off3, 63 );
lv_obj_set_align( ui_Pump_Off3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Pump_Off3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Pump_Off3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Pump_Off3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Pump_Off3, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Pump_Off3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Pump_Off3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Pump_Off3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Pump_Off3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Pump_Off3, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Pump_Off3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Pump_Off3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpButton2 = lv_imagebutton_create(ui_Pump_Off3);
lv_imagebutton_set_src(ui_pumpButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pumphigh_png, NULL);
lv_imagebutton_set_src(ui_pumpButton2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton2, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpButton2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpButton2, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpButton2, 100);
lv_obj_set_width( ui_pumpButton2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpButton2, 82 );
lv_obj_set_y( ui_pumpButton2, 20 );
lv_obj_set_align( ui_pumpButton2, LV_ALIGN_CENTER );

ui_pumpLabel3 = lv_label_create(ui_Pump_Off3);
lv_obj_set_width( ui_pumpLabel3, 100);
lv_obj_set_height( ui_pumpLabel3, 30);
lv_obj_set_x( ui_pumpLabel3, 41 );
lv_obj_set_y( ui_pumpLabel3, 47 );
lv_obj_set_align( ui_pumpLabel3, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_pumpLabel3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_pumpLabel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_pumpLabel3,"Spa Pump 1");
lv_obj_set_style_pad_left(ui_pumpLabel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pumpLabel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pumpLabel3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pumpLabel3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lamp9 = lv_obj_create(ui_High_Sample);
lv_obj_remove_style_all(ui_Lamp9);
lv_obj_set_width( ui_Lamp9, 104);
lv_obj_set_height( ui_Lamp9, 108);
lv_obj_set_x( ui_Lamp9, 60 );
lv_obj_set_y( ui_Lamp9, 63 );
lv_obj_set_align( ui_Lamp9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Lamp9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Lamp9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Lamp9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Lamp9, lv_color_hex(0x07F42C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Lamp9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Lamp9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Lamp9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Lamp9, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Lamp9, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Lamp9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lamp9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpLabel1 = lv_imagebutton_create(ui_Lamp9);
lv_imagebutton_set_src(ui_pumpLabel1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_pumphigh_png, NULL);
lv_imagebutton_set_src(ui_pumpLabel1, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpLabel1, LV_IMAGEBUTTON_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpLabel1, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imagebutton_set_src(ui_pumpLabel1, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_pumpoff_png, NULL);
lv_imagebutton_set_src(ui_pumpLabel1, LV_IMAGEBUTTON_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_pumpLabel1, 100);
lv_obj_set_width( ui_pumpLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_pumpLabel1, 82 );
lv_obj_set_y( ui_pumpLabel1, 20 );
lv_obj_set_align( ui_pumpLabel1, LV_ALIGN_CENTER );

}
