// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#include "../ui.h"

void ui_Spa_Screen_screen_init(void)
{
ui_Spa_Screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Spa_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Spa_Screen,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Spa_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Current_Temperature = lv_obj_create(ui_Spa_Screen);
lv_obj_set_width( ui_Current_Temperature, 150);
lv_obj_set_height( ui_Current_Temperature, 150);
lv_obj_set_x( ui_Current_Temperature, -1 );
lv_obj_set_y( ui_Current_Temperature, 0 );
lv_obj_set_flex_flow(ui_Current_Temperature,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Current_Temperature, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Current_Temperature, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Temp_History = lv_chart_create(ui_Spa_Screen);
lv_obj_set_width( ui_Temp_History, 150);
lv_obj_set_height( ui_Temp_History, 150);
lv_obj_set_align( ui_Temp_History, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Temp_History, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Temp_History, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Temp_History, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Temp_History, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Temp_History, LV_CHART_TYPE_LINE);

ui_Temp_History_Xaxis = lv_scale_create( ui_Temp_History );
lv_scale_set_mode( ui_Temp_History_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Temp_History_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Temp_History_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Temp_History_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Temp_History,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Temp_History,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Temp_History_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Temp_History_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Temp_History_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Temp_History_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Temp_History_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Temp_History_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Temp_History_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Temp_History_Xaxis, 2 >= 1 ? 2 : 1 );
ui_Temp_History_Yaxis1 = lv_scale_create( ui_Temp_History );
lv_scale_set_mode( ui_Temp_History_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Temp_History_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Temp_History_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Temp_History_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Temp_History,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Temp_History,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Temp_History_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Temp_History_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Temp_History_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Temp_History_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Temp_History_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Temp_History_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Temp_History_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_Temp_History_Yaxis2 = lv_scale_create( ui_Temp_History );
lv_scale_set_mode( ui_Temp_History_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Temp_History_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Temp_History_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Temp_History_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Temp_History,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Temp_History,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Temp_History_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Temp_History_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Temp_History_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Temp_History_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Temp_History_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Temp_History_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Temp_History_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_Temp_History_series_1 = lv_chart_add_series(ui_Temp_History, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Temp_History_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Temp_History, ui_Temp_History_series_1, ui_Temp_History_series_1_array);



//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Temp_History, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Temp_History, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Heater_History = lv_chart_create(ui_Spa_Screen);
lv_obj_set_width( ui_Heater_History, 150);
lv_obj_set_height( ui_Heater_History, 150);
lv_obj_set_align( ui_Heater_History, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Heater_History, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Heater_History, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Heater_History, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Heater_History, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Heater_History, LV_CHART_TYPE_LINE);

ui_Heater_History_Xaxis = lv_scale_create( ui_Heater_History );
lv_scale_set_mode( ui_Heater_History_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Heater_History_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Heater_History_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Heater_History_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Heater_History,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Heater_History,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Heater_History_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Heater_History_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Heater_History_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Heater_History_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Heater_History_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Heater_History_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Heater_History_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Heater_History_Xaxis, 2 >= 1 ? 2 : 1 );
ui_Heater_History_Yaxis1 = lv_scale_create( ui_Heater_History );
lv_scale_set_mode( ui_Heater_History_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Heater_History_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Heater_History_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Heater_History_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Heater_History,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Heater_History,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Heater_History_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Heater_History_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Heater_History_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Heater_History_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Heater_History_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Heater_History_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Heater_History_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_Heater_History_Yaxis2 = lv_scale_create( ui_Heater_History );
lv_scale_set_mode( ui_Heater_History_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Heater_History_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Heater_History_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Heater_History_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Heater_History,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Heater_History,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Heater_History_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Heater_History_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Heater_History_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Heater_History_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Heater_History_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Heater_History_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Heater_History_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_Heater_History_series_1 = lv_chart_add_series(ui_Heater_History, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Heater_History_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Heater_History, ui_Heater_History_series_1, ui_Heater_History_series_1_array);



//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Heater_History, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Heater_History, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Filter_History = lv_chart_create(ui_Spa_Screen);
lv_obj_set_width( ui_Filter_History, 150);
lv_obj_set_height( ui_Filter_History, 150);
lv_obj_set_align( ui_Filter_History, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Filter_History, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Filter_History, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Filter_History, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Filter_History, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Filter_History, LV_CHART_TYPE_LINE);

ui_Filter_History_Xaxis = lv_scale_create( ui_Filter_History );
lv_scale_set_mode( ui_Filter_History_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Filter_History_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Filter_History_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Filter_History_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Filter_History,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Filter_History,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Filter_History_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Filter_History_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Filter_History_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Filter_History_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Filter_History_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Filter_History_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Filter_History_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Filter_History_Xaxis, 2 >= 1 ? 2 : 1 );
ui_Filter_History_Yaxis1 = lv_scale_create( ui_Filter_History );
lv_scale_set_mode( ui_Filter_History_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Filter_History_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Filter_History_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Filter_History_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Filter_History,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Filter_History,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Filter_History_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Filter_History_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Filter_History_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Filter_History_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Filter_History_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Filter_History_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Filter_History_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_Filter_History_Yaxis2 = lv_scale_create( ui_Filter_History );
lv_scale_set_mode( ui_Filter_History_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Filter_History_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Filter_History_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Filter_History_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Filter_History,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Filter_History,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Filter_History_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Filter_History_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Filter_History_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Filter_History_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Filter_History_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Filter_History_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Filter_History_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_Filter_History_series_1 = lv_chart_add_series(ui_Filter_History, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Filter_History_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Filter_History, ui_Filter_History_series_1, ui_Filter_History_series_1_array);



//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Filter_History, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Filter_History, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Pump_1 = lv_button_create(ui_Spa_Screen);
lv_obj_set_width( ui_Pump_1, 100);
lv_obj_set_height( ui_Pump_1, 50);
lv_obj_set_x( ui_Pump_1, -189 );
lv_obj_set_y( ui_Pump_1, 169 );
lv_obj_set_align( ui_Pump_1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Pump_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Pump_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
