// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SPA

#ifndef _UI_COMP_UILIGHT_H
#define _UI_COMP_UILIGHT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT uiLight
#define UI_COMP_UILIGHT_UILIGHT 0
#define UI_COMP_UILIGHT_BUTTON 1
#define UI_COMP_UILIGHT_LABEL 2
#define _UI_COMP_UILIGHT_NUM 3
lv_obj_t *ui_uiLight_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
